FROM python:3.12.2
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN mkdir /app
WORKDIR /app

RUN apt update -y \
    && pip install --upgrade pip \
    && pip install Django==5.0.3 pip install djangorestframework==3.15.1 psycopg2 \
    && apt-get install -y postgresql-client
