FROM python:3.12.2
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN mkdir /app
WORKDIR /app

RUN apt update -y \
    && apt-get install -y postgresql-client

RUN pip install Django==5.0.3 djangorestframework==3.15.1 psycopg2 \
